### ISSUE TITLE
`read` seems to return samples from the past

### ISSUE THREAD

**Issue by mbaz** [JuliaTelecom/SoapySDR.jl#12]
The test setup is one laptop transmitting a sine wave using a B200 with gnuradio, and a second laptop receiving using an RTLSDR and SoapySDR.jl.

Samples are read from the RTLSDR using `Base.read(stream, 10_000)`.

This is the sequence of events:

1. B200 transmitting; RTLSDR returns a clean sine wave.
2. B200 off; RTLSDR returns the same sine wave.
3. Julia restarted; RTLSDR returns noise (as expected).
4. B200 transmitting; RTLSDR returns noise (expected a sine wave).
5. Julia restarted; RTLSDR returns a sine wave (as expected).

One explanation is that `read` returns old samples stored somewhere. The ideal behavior is that samples are discarded by default; when `read`ing, the specified number of samples are read from the device and returned; subsequent samples are discarded, until a new `read` is executed.

**Comment by sjkelly** [comment]
I wonder if this is related to #13. Can you see if the fix here helps: https://github.com/JuliaTelecom/SoapySDR.jl/issues/13#issuecomment-913234145

**Comment by mbaz** [comment]
@sjkelly Wrapping `read`s in between stream activation and de-activations helps.

**Comment by sjkelly** [comment]
Should be fixed in #22. Please comment or reopen if otherwise.
