### ISSUE TITLE
Int12 and Int4 Support

### ISSUE THREAD

**Issue by sjkelly** [JuliaTelecom/SoapySDR.jl#2]
Some devices, such as the xrtrx, have native 12 bit support. There is the choice to extend to 16 bit or shift to 8 bit, either of which are typically used with bandwidth/precision tradeoffs.

It would be nice to have Int12 support so no such tradeoff has to be made in environments with a surplus of processing power, and where bandwidth can be saturated.

**Comment by mbaz** [comment]
I'll leave this link here just in case: https://github.com/rfourquet/BitIntegers.jl
