### ISSUE TITLE
Fragment issues with multiple buffers

### ISSUE THREAD

**Issue by sjkelly** [JuliaTelecom/SoapySDR.jl#34]
With the `highlevel_loopback.jl` example, some devices with a packet interface such as the USRP fail to produce the expected result when using multiple buffers. This seems to be addressed by using a single large buffer.  

cc @mbaz who reported.

**Comment by sjkelly** [comment]
Note that there is a `SOAPY_SDR_MORE_FRAGMENTS` flag that is set in USRP: https://github.com/pothosware/SoapyUHD/blob/26b48cc11d3072b03b21793d980887a2e00091c8/SoapyUHDDevice.cpp#L292

It may be good to check this as well and modify our read loop accordingly.

**Comment by sjkelly** [comment]
Note: the USRP drivers have been updated in Julia. This issue was specifically mentioned in the UHD patch notes. Hopefully this is now fixed

**Comment by mbaz** [comment]
Since the LFSR RF loopback is working, I think we can close this and re-open if the problem resurfaces.
