### ISSUE TITLE
Use Clang.jl for bindings?

### ISSUE THREAD

**Issue by sjkelly** [JuliaTelecom/SoapySDR.jl#41]
I've only used Clang.jl a few times to generate bindings. It does seem to do a very good job and automates much of the process.

**Comment by RGerzaguet** [comment]
Hello @sjkelly. I can confirm, this is what I have used for  the new version of UHDBindings  and the RTLSDR part of AbstractSDRs. It does a wonderful job and is particularly precious for enumerations and tons of accessors/mutators.
